### PR TITLE
Automated install with Docker and Fig

### LINKED ISSUE #233: Automated install of mining
Add support to automated install using docker and fig to simplify the setup of new development and demo environments.

### PR DESCRIPTION
**Pull request by ayr-ton**
Fix #233

### CODE REVIEW

**Comment by ayr-ton** [comment]
Build problems during `fig up` can be related to #232 and mining/frontend#1

**Comment by ayr-ton** [comment]
@avelino Theres space in this pull request for I simplify the Dockerfile just calling the Makefile? If so, can I remove the Makefile step that copy the mining.example.ini? The reason is create a mining.fig.example.ini and explain in README.md to copy the example.ini if is a normal build or fig.example if is a docker build.
Also, I could update the README.md to encourage the use of the Makefile in manual builds too.

**Comment by ayr-ton** [comment]
@avelino Done. :sunglasses: 
Please, let me know if the manual process in REAME is okay.

**Comment by luzfcb** [comment]
@ayr-ton you seen the message on fig site?

> Fig has been replaced by Docker Compose, and is now deprecated. The [new documentation](http://docs.docker.com/compose/install) is on the Docker website.

**Comment by avelino** [comment]
@ayr-ton build failed, fix pls!

**Comment by ayr-ton** [comment]
@avelino Did you copy the mining.fig.sample.ini if you are trying the build with docker, or mining.sample.ini if you are trying the manual build?

**Comment by ayr-ton** [comment]
@luzfcb It works fine with docker compose if the fig.yml turn to docker-compose.yml.
Should I rename the file now?

**Comment by avelino** [comment]
yep rename!

**Comment by luizvital** [comment]
Tried to run with `fig` and the build stopped in mining setup install. Follows the error message:

```
byte-compiling build/bdist.linux-x86_64/egg/mining/utils/listc.py to listc.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy 'mining/mining.ini': doesn't exist or not a regular file
make: *** [install] Error 1
Service 'web' failed to build: The command [/bin/sh -c make install] returned a non-zero code: 2
```

I've added a `COPY mining/mining.sample.fig.ini mining/mining.ini` in the `Dockerfile`, but it's still failing

**Comment by luizvital** [comment]
`COPY` in `Dockerfile` now works. See this gist https://gist.github.com/luizvital/209dcb321387ba5302cc/revisions. Build failed for another reason:

```
bower                                           ECONFLICT Unable to find suitable version for angular
Service 'web' failed to build: The command [/bin/sh -c bower install --allow-root] returned a non-zero code: 1
```

**Comment by ayr-ton** [comment]
@luizvital It is related to this: https://github.com/mining/frontend/issues/1
I will submit a fix to that repo first.

**Comment by seagoat** [comment]
Fig has been replaced by Docker Compose, and is now deprecated. 
In the new fix, will Docker Compose be used?

**Comment by avelino** [comment]
@ayr-ton can you close this PR until when? I'm going back to move in the Open Mining still this month, it would be ideal that be closed as soon as possible!

**Comment by ayr-ton** [comment]
@avelino Yep

**Comment by avelino** [comment]
@ayr-ton will open another PR with the entire source?

**Comment by ayr-ton** [comment]
@avelino Of cource. I will just reopen this one. Or do you want new commits? More cleaner?

**Comment by ayr-ton** [comment]
@avelino Btw. I prefer to push a new branch with new commits.

**Comment by avelino** [comment]
@ayr-ton ok, It would be good to do as soon as possible!

**Comment by joaojunior** [comment]
Hi Guys, This pull request didn't accept? I'm looking for the dockerfile in this repo, but I don't find this.

**Comment by ayr-ton** [comment]
@joaojunior Thanks for remember me about this MR.
I will rewrite this and resend the Dockerfile according to the last build.

**Pull request closed without merging**
